---
name: Term-TUI
version: 1.22
author:
  - 'Sullivan Beck <sbeck@cpan.org>'
abstract: simple tool for building text-based user interfaces
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Term::ReadLine: 0
  Text::ParseWords: 0
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Term::TUI:
    file: lib/Term/TUI.pm
    version: 1.22
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
